project_id = "jdxzsocqbobguimsbhng"

[functions]
  [functions.asistente]
    verify_jwt = false
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.get-conversions-summary]
    verify_jwt = false
  [functions.process-email-queue]
    verify_jwt = true
  [functions.submit-appointment]
    verify_jwt = false
  [functions.track-conversion]
    verify_jwt = false
