// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-conditions.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { CONDITIONS } from "npm:@/data/treatments";
var list_conditions_default = defineTool({
  name: "list_conditions",
  title: "Listar condiciones tratadas",
  description: "Devuelve el cat\xE1logo de condiciones de dolor que trata ALGOS Centro de Dolor Intervencionista (nombre para paciente, nombre cl\xEDnico y resumen).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const items = CONDITIONS.map((c) => ({
      slug: c.slug,
      name: c.name,
      clinicalName: c.clinicalName,
      summary: c.patientDescription
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(items, null, 2) }],
      structuredContent: { items }
    };
  }
});

// src/lib/mcp/tools/get-condition.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^4.4.3";
import { CONDITIONS as CONDITIONS2 } from "npm:@/data/treatments";
var get_condition_default = defineTool2({
  name: "get_condition",
  title: "Detalle de una condici\xF3n",
  description: "Devuelve el detalle completo de una condici\xF3n de ALGOS: s\xEDntomas, cu\xE1ndo consultar, qu\xE9 esperar, procedimientos asociados y FAQ.",
  inputSchema: {
    slug: z.string().min(1).describe("Slug de la condici\xF3n (ej. dolor-lumbar-ciatica).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ slug }) => {
    const condition = CONDITIONS2.find((c) => c.slug === slug);
    if (!condition) {
      return {
        content: [
          {
            type: "text",
            text: `No existe una condici\xF3n con slug "${slug}". Usa list_conditions para ver los slugs disponibles.`
          }
        ],
        isError: true
      };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(condition, null, 2) }],
      structuredContent: { condition }
    };
  }
});

// src/lib/mcp/tools/list-procedures.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { PROCEDURES } from "npm:@/data/treatments";
var list_procedures_default = defineTool3({
  name: "list_procedures",
  title: "Listar procedimientos",
  description: "Devuelve el cat\xE1logo de procedimientos intervencionistas que realiza ALGOS (nombre, nombre t\xE9cnico, descripci\xF3n y condiciones en que se usan).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    return {
      content: [{ type: "text", text: JSON.stringify(PROCEDURES, null, 2) }],
      structuredContent: { items: PROCEDURES }
    };
  }
});

// src/lib/mcp/tools/list-team.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
import TEAM from "npm:@/data/team";
var list_team_default = defineTool4({
  name: "list_team",
  title: "Equipo cl\xEDnico",
  description: "Devuelve el equipo cl\xEDnico de ALGOS: miembros confirmados (nombre, rol, especialidad, ciudad) y perfiles en incorporaci\xF3n.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    return {
      content: [{ type: "text", text: JSON.stringify(TEAM, null, 2) }],
      structuredContent: { members: TEAM }
    };
  }
});

// src/lib/mcp/tools/clinic-info.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.20.0";
var INFO = {
  name: "ALGOS \xB7 Centro de Dolor Intervencionista",
  positioning: "Primer centro especializado en dolor intervencionista del Estado Zulia, Venezuela.",
  location: {
    city: "Maracaibo",
    state: "Zulia",
    country: "Venezuela",
    address: "Av. 20 con Calle 65, N\xB0 65-02, CC Am\xE9rica, Local 4"
  },
  contact: {
    whatsapp: "https://wa.me/584246467944",
    email: "info@algoscentrodolor.com"
  },
  website: "https://algoscentrodolor.com",
  alliance: {
    partner: "UDUZ",
    url: "https://uduz.vercel.app",
    role: "Diagn\xF3stico por imagen y electrodiagn\xF3stico (EEG, EMG). El paciente entra por ALGOS, se diagnostica en UDUZ y el procedimiento se realiza en ALGOS."
  }
};
var clinic_info_default = defineTool5({
  name: "clinic_info",
  title: "Informaci\xF3n de la cl\xEDnica",
  description: "Devuelve datos institucionales de ALGOS: ubicaci\xF3n, contacto oficial, sitio web y alianza estrat\xE9gica con UDUZ.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(INFO, null, 2) }],
    structuredContent: INFO
  })
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "algos-mcp",
  title: "ALGOS \xB7 Centro de Dolor Intervencionista",
  version: "0.1.0",
  instructions: "Herramientas de solo lectura sobre el contenido p\xFAblico de ALGOS Centro de Dolor Intervencionista (Maracaibo, Venezuela): condiciones tratadas, procedimientos intervencionistas, equipo cl\xEDnico y datos de contacto. Usa `list_conditions` y luego `get_condition` para responder preguntas de pacientes sobre s\xEDntomas, procedimientos, qu\xE9 esperar y cu\xE1ndo consultar.",
  tools: [list_conditions_default, get_condition_default, list_procedures_default, list_team_default, clinic_info_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
