import drAtilioAsset from "@/assets/Atilio_foto_cortada.png.asset.json";
import photoAtilio   from "@/assets/team/doctor-atilio.png";
import photoAntulio  from "@/assets/team/doctor-antulio.png";
import photoTomas    from "@/assets/team/doctor-tomas.png";
import photoLeslie   from "@/assets/team/doctor-leslie.png";
import photoCarolina from "@/assets/team/doctor-carolina.png";

import photoDaniel   from "@/assets/team/doctor-daniel.png";

// Picture import type (as generated by vite-imagetools `as=picture`)
export type PictureImport = {
  sources: Record<string, string>;
  img: { src: string; w: number; h: number };
};

export type Doctor = {
  slug: string;
  name: string;
  /** Etiqueta larga mostrada en tarjetas del equipo. */
  specialty: string;
  /** Slug de la especialidad a la que pertenece (coincide con SPECIALTIES en specialties.ts). */
  specialtySlug:
    | "neurocirugia"
    | "traumatologia"
    | "reumatologia"
    | "fisiatria"
    | "cuidados-paliativos"
    | "psicologia"
    | "nutricion";
  schedule: string;
  note?: string;
  isDirector?: boolean;
  photo?: PictureImport;
  photoPosition?: string;
  /** URL directa de la foto de perfil (desde assets/team/). */
  photoSrc?: string;
  /** Biografía / presentación breve para el perfil individual. */
  bio?: string;
  /** Credenciales, formación, cargos previos. */
  credentials?: string[];
  /** Idiomas de atención. */
  languages?: string[];
};

/**
 * Fuente única de verdad del equipo clínico de ALGOS.
 * Cualquier componente que muestre médicos debe importarse desde aquí.
 */
export const DOCTORS: Doctor[] = [
  {
    slug: "dr-atilio-rodriguez",
    name: "Dr. Atilio Rodríguez",
    specialty: "Neurocirugía y cirugía de columna · Director Médico",
    specialtySlug: "neurocirugia",
    schedule: "Lunes, martes, jueves y viernes · 1:00 PM - 4:00 PM",
    isDirector: true,
    photo: { sources: {}, img: { src: drAtilioAsset.url, w: 414, h: 424 } },
    photoPosition: "center top",
    photoSrc: photoAtilio,
    bio: "Neurocirujano fundador y Director Médico de ALGOS. Lidera el enfoque intervencionista del centro: procedimientos guiados por imagen para tratar el dolor de columna y nervios cuando la cirugía todavía no hace falta.",
    credentials: [
      "Neurocirujano, Universidad del Zulia",
      "Especialista en dolor intervencionista y cirugía de columna",
      "Director Médico · ALGOS Centro de Dolor",
    ],
    languages: ["Español"],
  },
  {
    slug: "dr-antulio-parra",
    name: "Dr. Antulio Parra",
    specialty: "Traumatología y Ortopedia",
    specialtySlug: "traumatologia",
    schedule: "Martes y jueves · 8:00 AM - 11:00 AM",
    photoSrc: photoAntulio,
  },
  {
    slug: "dr-tomas-iragorry",
    name: "Dr. Tomás Iragorry",
    specialty: "Traumatología y Ortopedia",
    specialtySlug: "traumatologia",
    schedule: "Lunes, martes y miércoles · 8:00 AM - 12:00 PM",
    photoSrc: photoTomas,
    bio: "Traumatólogo Ortopedista con Fellowship en Traumatología Deportiva, entrenamiento en ecografía músculo-esquelética y certificación en Medicina del Fútbol FIFA-CONMEBOL. Miembro activo de la SVCOT, aporta al equipo de ALGOS un enfoque de alta precisión para lesiones del aparato locomotor tanto en pacientes deportivos como en dolor crónico musculoesquelético.",
    credentials: [
      "Médico Traumatólogo Ortopedista",
      "Miembro · Sociedad Venezolana de Cirugía Ortopédica y Traumatológica (SVCOT)",
      "Fellowship en Traumatología Deportiva",
      "Certificado en Medicina del Fútbol · FIFA-CONMEBOL",
      "Entrenamiento en Ecografía Músculo-Esquelética",
    ],
    languages: ["Español"],
  },
  {
    slug: "dr-miguel-guevara",
    name: "Dr. Miguel Guevara",
    specialty: "Traumatología y Ortopedia",
    specialtySlug: "traumatologia",
    schedule: "Lunes · 8:00 AM - 10:00 AM",
  },
  {
    slug: "dra-doris-meneses",
    name: "Dra. Doris Meneses",
    specialty: "Reumatología",
    specialtySlug: "reumatologia",
    schedule: "Viernes · 8:00 AM - 12:00 PM",
    bio: "Médico Reumatólogo especializado en el diagnóstico y manejo de enfermedades articulares y autoinmunes que cursan con dolor crónico. En ALGOS evalúa pacientes con artritis, fibromialgia, espondiloartritis y otros síndromes reumáticos, coordinando su tratamiento con el equipo intervencionista cuando procede.",
    credentials: [
      "Médico Reumatólogo",
      "Especialista en enfermedades articulares y autoinmunes",
    ],
    languages: ["Español"],
  },
  {
    slug: "dra-leslie-ramirez",
    name: "Dra. Leslie Ramírez",
    specialty: "Fisiatría y rehabilitación",
    specialtySlug: "fisiatria",
    schedule: "Jueves · 2:00 PM",
    photoSrc: photoLeslie,
    bio: "Médico Fisiatra especializada en Medicina Física y Rehabilitación, con base en Maracaibo. En ALGOS diseña y supervisa programas de rehabilitación individualizados que acompañan la recuperación funcional de los pacientes tras procedimientos intervencionistas.",
    credentials: [
      "Médico Fisiatra",
      "Especialista en Medicina Física y Rehabilitación",
    ],
    languages: ["Español"],
  },
  {
    slug: "dra-carolina-rodriguez",
    name: "Dra. Carolina Rodríguez",
    specialty: "Fisiatría, rehabilitación y estudios electromiográficos",
    specialtySlug: "fisiatria",
    schedule: "Miércoles tarde",
    photoSrc: photoCarolina,
    bio: "Fisiatra especializada en rehabilitación física personalizada, electrodiagnóstico y ozonoterapia. Miembro de la Sociedad Venezolana de Ozonoterapia, integra estudios electromiográficos y técnicas avanzadas de rehabilitación neuromuscular para acompañar la recuperación funcional de los pacientes de ALGOS.",
    credentials: [
      "Médico Fisiatra · Medicina Física y Rehabilitación",
      "Miembro · Sociedad Venezolana de Ozonoterapia",
      "Especialista en Estudios Electromiográficos (EMG)",
      "Rehabilitación física personalizada y neuromuscular",
    ],
    languages: ["Español"],
  },
  {
    slug: "dra-gilda-gomez",
    name: "Dra. Gilda Gómez",
    specialty: "Algología",
    specialtySlug: "cuidados-paliativos",
    schedule: "Miércoles · 9:00 AM - 12:00 PM",
    bio: "Algóloga con más de cuatro décadas en el Hospital Central 'Dr. Urquinaona' de Maracaibo, donde fundó el Servicio de Terapia del Dolor. En ALGOS integra protocolos de algología y cuidados paliativos para pacientes con dolor crónico complejo.",
    credentials: [
      "Médico Anestesióloga · Especialista en Terapia del Dolor",
      "Fundadora y Jefa de Terapia del Dolor · Hospital Central 'Dr. Urquinaona', Maracaibo",
      "Jefa del Dpto. de Anestesiología y Terapia del Dolor · H.C. 'Dr. Urquinaona' (2011–actualidad)",
      "Directora Médica · Hospice Venezuela, Fundación pacientes oncológicos terminales (2009–2013)",
      "Médica asesora · Fundación Zuliana Fibromialgia, Maracaibo (2010–actualidad)",
    ],
    languages: ["Español"],
  },
  {
    slug: "lcdo-daniel-rodriguez",
    name: "Lic. Daniel Rodríguez",
    specialty: "Nutrición Clínica Antiinflamatoria",
    specialtySlug: "nutricion",
    schedule: "Lunes, martes, jueves y viernes · 1:00 PM - 4:00 PM",
    isDirector: true,
    photoSrc: photoDaniel,
    bio: "Licenciado en Nutrición y Dietética. Acompaña al paciente intervencionista con un plan antiinflamatorio individualizado, enfocado en apoyar la recuperación y reducir factores metabólicos que sostienen el dolor.",
    credentials: [
      "Licenciado en Nutrición y Dietética",
      "Especialista en nutrición clínica antiinflamatoria",
      "Director de Nutrición · ALGOS Centro de Dolor",
    ],
    languages: ["Español"],
  },
];

export function getDoctorsBySpecialty(slug: Doctor["specialtySlug"]): Doctor[] {
  return DOCTORS.filter((d) => d.specialtySlug === slug);
}

export function getDoctorBySlug(slug: string): Doctor | undefined {
  return DOCTORS.find((d) => d.slug === slug);
}

// Validación en tiempo de build: si los datos son inconsistentes,
// `vite build` y `vite dev` abortan con un error legible.
// Import diferido para evitar dependencias circulares.
import { validateTeamData } from "@/data/validate";
validateTeamData(DOCTORS);
