import drAtilioPic from "@/assets/dr-atilio-full.png?w=320;480;720&format=avif;webp;jpg&as=picture";
import teamDanielPic from "@/assets/team-daniel.png?w=320;480;720&format=avif;webp;jpg&as=picture";

// Picture import type (as generated by vite-imagetools `as=picture`)
export type PictureImport = typeof drAtilioPic;

export type Doctor = {
  slug: string;
  name: string;
  /** Etiqueta larga mostrada en tarjetas del equipo. */
  specialty: string;
  /** Slug de la especialidad a la que pertenece (coincide con SPECIALTIES en specialties.ts). */
  specialtySlug:
    | "neurocirugia"
    | "traumatologia"
    | "reumatologia"
    | "fisiatria"
    | "cuidados-paliativos"
    | "psicologia"
    | "nutricion";
  schedule: string;
  note?: string;
  isDirector?: boolean;
  photo?: PictureImport;
  photoPosition?: string;
  /** Biografía / presentación breve para el perfil individual. */
  bio?: string;
  /** Credenciales, formación, cargos previos. */
  credentials?: string[];
  /** Idiomas de atención. */
  languages?: string[];
};

/**
 * Fuente única de verdad del equipo clínico de ALGOS.
 * Cualquier componente que muestre médicos debe importarse desde aquí.
 */
export const DOCTORS: Doctor[] = [
  {
    slug: "dr-atilio-rodriguez",
    name: "Dr. Atilio Rodríguez",
    specialty: "Neurocirugía y cirugía de columna · Director Médico",
    specialtySlug: "neurocirugia",
    schedule: "Lunes, martes, jueves y viernes · 1:00 PM – 4:00 PM",
    isDirector: true,
    photo: drAtilioPic,
    photoPosition: "center top",
    bio: "Neurocirujano fundador y Director Médico de ALGOS. Lidera el enfoque intervencionista del centro: procedimientos guiados por imagen para tratar el dolor de columna y nervios cuando la cirugía todavía no hace falta.",
    credentials: [
      "Neurocirujano — Universidad del Zulia",
      "Especialista en dolor intervencionista y cirugía de columna",
      "Director Médico · ALGOS Centro de Dolor",
    ],
    languages: ["Español"],
  },
  {
    slug: "dr-antulio-parra",
    name: "Dr. Antulio Parra",
    specialty: "Traumatología y Ortopedia",
    specialtySlug: "traumatologia",
    schedule: "Martes y jueves · 8:00 AM – 11:00 AM",
  },
  {
    slug: "dr-tomas-iragorry",
    name: "Dr. Tomás Iragorry",
    specialty: "Traumatología y Ortopedia",
    specialtySlug: "traumatologia",
    schedule: "Lunes, martes y miércoles · 8:00 AM – 12:00 PM",
  },
  {
    slug: "dr-miguel-guevara",
    name: "Dr. Miguel Guevara",
    specialty: "Traumatología y Ortopedia",
    specialtySlug: "traumatologia",
    schedule: "Lunes · 8:00 AM – 10:00 AM",
  },
  {
    slug: "dra-doris-meneses",
    name: "Dra. Doris Meneses",
    specialty: "Reumatología",
    specialtySlug: "reumatologia",
    schedule: "Viernes · 8:00 AM – 12:00 PM",
  },
  {
    slug: "dra-leslie-ramirez",
    name: "Dra. Leslie Ramírez",
    specialty: "Fisiatría y rehabilitación",
    specialtySlug: "fisiatria",
    schedule: "Jueves · 2:00 PM",
  },
  {
    slug: "dra-carolina-rodriguez",
    name: "Dra. Carolina Rodríguez",
    specialty: "Fisiatría, rehabilitación y estudios electromiográficos",
    specialtySlug: "fisiatria",
    schedule: "Miércoles tarde",
    note: "Los estudios EEG se realizan en UDUZ",
  },
  {
    slug: "dra-gilda-gomez",
    name: "Dra. Gilda Gómez",
    specialty: "Algología, anestesiología y cuidados paliativos",
    specialtySlug: "cuidados-paliativos",
    schedule: "Miércoles · 9:00 AM – 12:00 PM",
  },
  {
    slug: "lcdo-daniel-rodriguez",
    name: "Lic. Daniel Rodríguez",
    specialty: "Nutrición Clínica Antiinflamatoria",
    specialtySlug: "nutricion",
    schedule: "Lunes, martes, jueves y viernes · 1:00 PM – 4:00 PM",
    isDirector: true,
    photo: teamDanielPic,
    photoPosition: "center 20%",
    bio: "Licenciado en Nutrición y Dietética. Acompaña al paciente intervencionista con un plan antiinflamatorio individualizado, enfocado en apoyar la recuperación y reducir factores metabólicos que sostienen el dolor.",
    credentials: [
      "Licenciado en Nutrición y Dietética",
      "Especialista en nutrición clínica antiinflamatoria",
      "Director de Nutrición · ALGOS Centro de Dolor",
    ],
    languages: ["Español"],
  },
];

export function getDoctorsBySpecialty(slug: Doctor["specialtySlug"]): Doctor[] {
  return DOCTORS.filter((d) => d.specialtySlug === slug);
}

export function getDoctorBySlug(slug: string): Doctor | undefined {
  return DOCTORS.find((d) => d.slug === slug);
}
